// Generated by Wrangler on Tue Apr 09 2024 23:31:00 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  CULEFILO_KV: KVNamespace;
  ENVIRONMENT: string;
  PLACES_API_URL: string;
  OPENDATASOFT_API_URL: string;
  BUGSNAG_API_KEY: string;
  PLACES_API_KEY: string;
  AUTOCOMPLETE_API_KEY: string;
  AI: unknown;
}
