// Generated by Wrangler on Sun Apr 07 2024 18:40:16 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  CULEFILO_KV: KVNamespace;
  AI: unknown;
  OPENDATASOFT_API_URL: string; // updated manually
  PLACES_API_URL: string; // updated manually
  PLACES_API_KEY: string; // updated manually
  BUGSNAG_API_KEY: string; // updated manually
  AI_DEFAULT_INSTRUCTION: string; // updated manually
  ENVIRONMENT: string; //updated manually
}
