// Generated by Wrangler on Tue Apr 09 2024 18:46:44 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	CULEFILO_KV: KVNamespace;
	ENVIRONMENT: string;
	PLACES_API_URL: string;
	OPENDATASOFT_API_URL: string;
	BUGSNAG_API_KEY: string;
	PLACES_API_KEY: string;
	AI: unknown;
}
